Document: seeta-tennis
Title: Debian seeta-tennis Manual
Author: <insert document author here>
Abstract: This manual describes what seeta-tennis is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/seeta-tennis/seeta-tennis.sgml.gz

Format: postscript
Files: /usr/share/doc/seeta-tennis/seeta-tennis.ps.gz

Format: text
Files: /usr/share/doc/seeta-tennis/seeta-tennis.text.gz

Format: HTML
Index: /usr/share/doc/seeta-tennis/html/index.html
Files: /usr/share/doc/seeta-tennis/html/*.html
